version: '2'

services:

  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      trabalho_fametro:
            ipv4_address: 172.12.0.8  
          
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      trabalho_fametro:
            ipv4_address: 172.12.0.7  
            
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'project_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      trabalho_fametro:
            ipv4_address: 172.12.0.5  
            
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
        trabalho_fametro:
              ipv4_address: 172.12.0.3  
volumes:
  my-db:
    driver: local

networks:
  trabalho_fametro:
    driver: bridge
    ipam:
     config:
       - subnet: 172.12.0.0/16
         gateway: 172.12.0.1